name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install red_knot
        run: |
          cargo install red_knot --git https://github.com/astral-sh/ruff.git
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Run static analysis
        run: red_knot check .
      - name: Run tests
        run: pytest