name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install linters and type checker
        run: |
          pip install ruff mypy pyright
      - name: Ruff (lint)
        run: ruff check .
      - name: MyPy (type check)
        run: mypy .
      - name: Pyright (type check)
        run: pyright --project pyproject.toml
      - name: Run tests
        run: pytest
